name: Unit Tests JavaScript
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node configuration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: NPM Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Prepare env
      run: |
        npm install
    - name: Build and test
      run: |
        npm run test --coverage
    - uses: actions/upload-artifact@master
      with:
        name: code-coverage-artifact-js
        path: coverage
    - name: Codecov update
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -cF javascript
