name: Unit tests JavaScript
on: [push, pull_request, repository_dispatch]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node configuration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Prepare env
      run: |
        yarn
    - name: Build and test
      run: |
        yarn test --coverage