name: UTs_iOS_feature
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro']
          xcode: ['/Applications/Xcode_11.3.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache Pods
        id: pods-cache
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Prepare env (install pods)
        run: |
          cd ios
          pod install
      - name: Prepare env (install slather)
        run: |
          cd ios
          gem install slather
      - name: Build and test
        run: |
          cd ios
          xcodebuild clean build test -workspace RNMagicScript.xcworkspace -scheme RNMagicScriptHostApplication -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -derivedDataPath Build/ -enableCodeCoverage YES || exit 1
        env:
         destination: ${{ matrix.destination }}
         DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Code Coverage
        run: |
          cd ios
          slather | grep "Test Coverage:"
