name: Unit tests Android
on: [push]
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node configuration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Prepare env
      run: |
        cd android
        chmod u+x gradlew
        mkdir node_modules
        cd node_modules 
        yarn add react-native
    - name: Build and test
      run: |
        cd android
        ./gradlew jacocoTestReport
    - uses: actions/upload-artifact@master
      with:
        name: code-coverage-artifact-android
        path: android/build/reports/jacoco/jacocoTestReport/html
