name: UTs_Android_master
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node configuration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Prepare env
      run: |
        cd android
        chmod u+x gradlew
        mkdir node_modules
        cd node_modules
        npm install react-native
    - name: Build and test
      run: |
        cd android
        ./gradlew jacocoTestReport
    - uses: actions/upload-artifact@master
      with:
        name: code-coverage-artifact-android
        path: android/build/reports/jacoco/jacocoTestReport
    - name: Codecov update
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -cF kotlin
