name: Unit tests JavaScript
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node configuration
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Prepare env
      run: |
        yarn
    - name: Build and test
      run: |
        yarn test --coverage
    - uses: actions/upload-artifact@master
      with:
        name: code-coverage-artifact-js
        path: coverage
    - name: Codecov update
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -cF javascript
